services:
  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - ./data:/var/lib/mysql
